### ISSUE TITLE
Run parallelized spapros

### ISSUE THREAD

**Issue by simomounir** [theislab/spapros#260]
**Is your feature request related to a problem? Please describe.**

Is there any way to successfully run the parallelized version of Probeset Evaluation as shown in the tutorial? 
You also mentioned it briefly in the tutorial regarding the Probeset Evaluation examples and Spapros documentation.

**Describe the solution you would like**

Is there anyting I am missing? If the code snippet looks correct, is there any plan to fix this? 
**Additional context**

The code in question:

**

parallelized:
evaluator = sp.ev.ProbesetEvaluator(adata)

evaluator.compute_or_load_shared_results()

evaluator.evaluate_probeset(probeset, set_id, update_summary=False, pre=True) # parallelised over set_ids

evaluator.evaluate_probeset(probeset, set_id, update_summary=False) #

evaluator.summary_statistics()
**

Thanks :)

**Comment by LouisK92** [comment]
The parallelization written in that code snippet refers to a setup to run the code over multiple compute nodes in parallel. I.e. you need to wrap the individual steps in scripts. Are you intending to run code on such multi node setup?

Otherwise for one node most evaluation metrics are already parallelized you can control it with `n_jobs` in `spapros.ev.ProbesetEvaluator` (default is already `n_jobs=-1`, i.e. the number of available cores)

**Comment by LouisK92** [comment]
Closing for now. We also have a snakemake pipeline now that runs selections and evaluations in a parallized manner: https://github.com/theislab/spapros-smk
