### ISSUE TITLE
Design probe panels for multiple experiments

### ISSUE THREAD

**Issue by nikofleischer** [theislab/spapros#267]
**Question**
Hi, 
thanks a lot for your great work. 

We are currently working on implementing Xenium into our lab workflow. For this we have to develop custom gene panels, to cover our tissues of interest. Is it possible to design probesets that span multiple different experimental questions using Spapros? We have scRNAseq data either in house or publically available for all subcompartments and different states of the tissue we're interested in. Still, they have been generated using different technologies across multiple labs. 

What would be the most sensible way to tackle this issue? Would it make sense to set the number of genes lower and generate separate probe selections for each question of interest that are then combined into one panel?  

Or would it be better to try and integrate the data from all different datasets? Unfortunately, there is Snuc and scRNAseq data, generated using SmartSeq as well as 10X 3' chemistries, so I would expect large batch effects between the different studies. 

Thanks a lot for your help,
Niko

**Comment by LouisK92** [comment]
Hi Niko,

sorry for the late answer! Didn't realize that my github notifications suddenly went to spam instead of inbox.

Indeed using a lot of datasets can make panel selections quite challenging.

One important question is: Are your cell type annotations over data sets unified? If not, then a per dataset selection is needed when using Spapros. In that case I'd set `n=None` for each selection. You get a ranked list for each dataset. Then I'd generate a consensus ranking based on those lists.

Assuming you have unified cell type annotations:
The batch effects between the scRNAseq reference datasets is an issue we're looking into. From our experience the batch effects don't cause large problems with respect to variation between cell types, this selection is quite robust besides batch effects. However, for general variation beyond cell type annotations you select a few more genes that are more aligned with batch variation compared to within-batch variation. We're working on a solution for that (that also facilities selections on many datasets), but right now either accepting that some selected genes are more optimised for batch variation or building a consensus from per dataset selections are the ways to go. 

Since now Xenium panels also have a quite high number of genes, I'd recommend to check section iii of our advanced selection tutorial: https://spapros.readthedocs.io/en/latest/_tutorials/spapros_tutorial_advanced_selection.html#iii.-Selection-for-high-numbers-of-genes-(%3E-150) . 
So my recommendation for your setup would be:
- in case of unified cell types: 1. cell type only (`n_pca_genes=0`) selection (n = ~100) based on all datasets merged 2. Extend list with a consensus selection as described above (filter out the genes already selected in 1. before the 2. selection)
- in case of non-unified cell types: exchange 1. with a cell type only consensus selection over datasets, then 2.
- and in general it's typically a good idea to add prior knowledge genes that are tailored towards your scientific question

I hope that helps, let me know if you have more questions.

**Comment by LouisK92** [comment]
Closing for now, please let me know if you want to discuss further.

**Comment by nikofleischer** [comment]
Thanks a lot for the input. Currently, there are no unified annotations, as tissues, platforms, and chemistries differ wildly. I will try out your tips under 2. and get back if any questions arise :) 

Best, Niko
