### ISSUE TITLE
identification of spatial genes (genes expressed by different cell types)

### ISSUE THREAD

**Issue by shobhitagrawal1** [theislab/spapros#386]
Hi, 
Congrats on the publication and thank you for this tool. 
I looked through the paper and the tutorials, and maybe I missed it, I would be grateful if you could just provide a bit of information regarding genes with potential of identifying spatial heterogeneity. 
thanking you
shobhit

**Comment by LouisK92** [comment]
Hey! Thanks:)

The scRNA-seq reference itself doesn't give you directly the information which transcriptional variation translates into spatial variation. The way we go about this is by saying, if you optimize for transcriptional variation recovery in general you increase the likelihood to find spatially variable signals. It could depend a bit on how to define spatially variable - and we look from different angles at this. We show in three analyses that optimizing for variation recovery on scRNA-seq does correlate with spatial variation capture:
Based on sub selections of a 4000 genes merfish dataset we look at two metrics:
- moran's I (Extended Data Figure 3b), which measures if a gene's spatial distribution is patterned or rather randomly distributed over space.
- cell-cell interaction score (CCI score, Fig 4e). This one is based on NCEM models from which you can infer for each gene what part of the variation is explained by the cell's niche composition (i.e. neighboring cells).
So for these two metrics we find the trend that optimizing variation recovery for scRNA-seq also increases the capture of these spatially relevant signals.
Lastly, in our example on the measured scrinshot data (Fig3c-e) we show examples of genes with gradients within cell types that show spatial variation in the given cell type. Such genes that refer rather to cell states, multicellular programs, and/or differentiation transitions are selected by methods that recover general variation (e.g. Spapros, SCMER, geneBasis but not so much with e.g. SpaprosCTo, DE, etc.).

**Comment by shobhitagrawal1** [comment]
Thank you for your prompt reply and the detailed expalanation. Highly appreciated.
I do get that you verify which genes are spatially vairable - a posterori through Moran's I and CCI scores, I was just wondering how to identify non-cell specific genes in the results table i.e. potential candidates for spatial variation. Are these genes which have empty values in the "celltypes_marker", identifiying them as potentially useful genes which identify "some" variation in the data but are not specifically marker genes for celltypes?
Use case: I have subdivisions of sub-organ of the brain for which I snRNA data, the sub-organs share most cell-types but these types carry signals which are possibly organ-specific. The idea is to use spapros to design a gene panel which recovers these signals in the snRNA data and can be eventually used for validation through spatial-seq methods. In general and documentation is great, thanks for that. 
One more question- how can I obtain the heirarchical tree which is used by the program, by extension- gene based and overall trees? 
Sorry for the bother, and thank you once again.
Shobhit

**Comment by LouisK92** [comment]
Ah I see!

**Identify candidate genes for spatial variation within cell types:**
We don't define clear categories that distinguish markers and such genes that rather capture within-cell type variation. However, from the resulting table you can use some scores to rank genes on that regard.   
- Your suggestion using genes without values in "cell types_marker" is one option, yes
- maybe better is ranking genes based on lowest `"importance_score"` and highest `"pca_score"`, this you can achieve via:

```python
import spapros as sp

selector = sp.se.ProbesetSelector(...)
selector.select_probeset()

df = selector.probeset

print(df[df["selection"]].sort_values(['importance_score',"pca_score"],ascending=[True,False]))
# or
# print(df[~df['importance_score'].isnull()].sort_values(['importance_score',"pca_score"],ascending=[True,False]))

```

This gives you a ranking - still good to look at those genes in detail though (e.g. expression in umap). 

Here again, this is about variation within cell types, independent of spatial variation - but as mentioned (Moran's I, CCI score, etc.) these genes are good candidates for spatial variation within cell types.

Spapros will give an optmised trade-off over the full dataset, including e.g. multi cellular program genes. If you are additionally interested in a specific cell type of you snRNAseq data and want to put more focus on the variation within that cell type, you could additionally do a [PCA selection](https://spapros.readthedocs.io/en/latest/se/spapros.se.select_pca_genes.html#spapros.se.select_pca_genes) on that data subset  - default parameters do the job. It just gives you a ranking, the top genes are the most interesting ones.

**How to obtain the hierarchical trees:**
All genes that occur in a given cell type's hierarchical trees you can get from 
```python
selector._get_genes_of_primary_trees()
```
The `"importance score"` tells one how important that gene is for the identification of the given cell type (according it's decision tree rules). Genes with a lower score might not be too important. The `"nr_of_celltypes"` column just gives the info for how many cell types the gene was used in their trees (i.e. `selector._get_genes_of_primary_trees()["gene"].value_counts()`).

Regarding your question for retrieving the actual trees: Currently I haven't implemented a quick way to retrieve the hierarchical tree, even though single trees are saved - but the main purpose of that is for loading them in in case the selection was interrupted, so it doesn't need to start from the beginning. If you have a specific use case I can have a look into implementing a utility function.

An additional note on the combinatorial rules for cell type identification: Ultimately I just look at the gene set of the tree for classification on spatial data instead of the exact decision tree thresholding since you have expression level modality differences between scRNAseq and the spatial data. Therefore whenever we talked about combinatorial rules in the manuscript we are mainly referring to the gene set of the tree (`selector._get_genes_of_primary_trees()`) instead of the exact function. But I do see that having the exact trees is also interesting.

**Comment by shobhitagrawal1** [comment]
Spectacular! Thank you very much. Really appreciate the effort on providing details

**Comment by LouisK92** [comment]
Happy to! Thanks for your interest in the method. 

Closing the issue for now, let me know in case of additional questions
